### DISCUSSION TITLE
Support `rustc_codegen_cranelift`

### DISCUSSION THREAD

**Discussion by AccessViolation95** [pacak/cargo-show-asm#287] [Q&A] [answered]
It would be nice if cargo-show-asm supported `rustc_codegen_cranelift`. It would be useful for comparing the output of Cranelift and LLVM.

In order to make rustc use Cranelift, I have installed it following these instructions: https://github.com/rust-lang/rustc_codegen_cranelift

My project's `Cargo.toml` looks like this:
```toml
# This line needs to come before anything else in Cargo.toml
cargo-features = ["codegen-backend"]

[package]
name = "quick_test"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-backend = "cranelift"
```
The output I get when running `cargo asm` is:
```
error: Unknown option `-x86-asm-syntax`

error: could not compile `quick_test` (bin "quick_test") due to 1 previous error

Cargo failed with exit status: 101
```
