### ISSUE TITLE
.cargo/config doesn't seem to be taken into account

### ISSUE THREAD

**Issue by emoon** [pacak/cargo-show-asm#364]
Hi,

First of all thanks for a great tool. Something I noticed is that the tool doesn't seem to take `.cargo/config` into account when generating the code.

To reproduce this I have a `.cargo/config` that looks like this

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+sse4.2,+ssse3"]
```
and an example project called `test_asm` with some code that looks like this (notice this code only works on x86/64 systems)
```Rust
use core::arch::x86_64::*;

#[inline(never)]
fn mulh(a: __m128i, b: __m128i) -> __m128i {
    unsafe { _mm_mulhrs_epi16(a, b) }
}

fn main() {
    unsafe {
        let a = _mm_set1_epi16(0x1234);
        let b = _mm_set1_epi16(0x5678);
        core::hint::black_box(&a);
        let c = mulh(a, b);
        println!("{:?}", c);
    }
}
```
When doing `cargo asm test_asm::mulh` I get
```asm
test_asm::mulh:
        .cfi_startproc
        sub rsp, 40
        .cfi_def_cfa_offset 48
        movaps xmmword ptr [rsp], xmm0
        movaps xmmword ptr [rsp + 16], xmm1
        mov rsi, rsp
        lea rdx, [rsp + 16]
        call core::core_arch::x86::ssse3::_mm_mulhrs_epi16
        add rsp, 40
        .cfi_def_cfa_offset 8
        ret
```
but if I compile the code as regular with `cargo build --release` and then do a objdump on the executable get `test_asm::mul` (mangled) looks like this
```asm
0000000000007930 <_ZN8test_asm4mulh17h5dcf14d1a88ca589E>:
    7930:	66 0f 38 0b 05 c7 f6 	pmulhrsw xmm0,XMMWORD PTR [rip+0x3f6c7]        # 47000 <_fini+0x5f4>
    7937:	03 00 
    7939:	66 0f 7f 07          	movdqa XMMWORD PTR [rdi],xmm0
    793d:	c3                   	ret
```
Which is the expected output. I wonder if I'm missing something here?

Update:

If I manually set the flags and do like this `RUSTFLAGS="-C target-feature=+sse4.2,+ssse3" cargo asm test_asm::mulh` it also works:
```asm
test_asm::mulh:
        .cfi_startproc
        pmulhrsw xmm0, xmm1
        movdqa xmmword ptr [rdi], xmm0
        ret
```
But it would be great if `.cargo/config` could be taken into account.
